Adapted to bs58check V4 new interface
This corrects extended public decoding which crashed with error: TypeError: bs58check.decode is not a function.

Regression can be tested with xpub6CpihtY9HVc1jNJWCiXnRbpXm5BgVNKqZMsM4XqpDcQigJr6AHNwaForLZ3kkisDcRoaXSUms6DJNhxFtQGeZfWAQWCZQe1esNetx5Wqe4M on public demo.

Additionally set version 1.7.4 for axios to correct vulnerability detected by npm audit